name: Sync Secrets

on:
  workflow_dispatch:
    inputs:
      sync_env:
        description: 'Sync .env file with GitHub Secrets'
        required: true
        default: 'true'

jobs:
  sync-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Sync .env with GitHub Secrets
        uses: fergusfrl/getsecret@1.0.0
        with:
          file_path: '.env'
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
